<link rel="stylesheet" type="text/css" href="../css/style.css"/>
<link rel="stylesheet" type="text/css" href="../css/content.css"/>
<link rel="stylesheet" type="text/css" href="../css/common.css"/>
<link rel="stylesheet" type="text/css" href="../css/jquery-ui-1.9.0.custom.css"/>
<link rel="stylesheet" type="text/css" href="../css/jbox_Green/jbox.css"/>
<script language="javascript" type="text/javascript" src="../js/general.js"></script>
<script language="javascript" type="text/javascript" src="../js/jquery-1.8.2.js"></script>
<script language="javascript" type="text/javascript" src="../js/jquery-ui-1.9.0.custom.js"></script>
<script language="javascript" type="text/javascript" src="../js/jquery.form.js"></script>
<script language="javascript" type="text/javascript" src="../js/jquery.jBox-2.3.min.js"></script>
<script language="javascript" type="text/javascript" src="../js/jquery.jBox-zh-CN.js"></script>
<script language="javascript" type="text/javascript" src="../js/common.js"></script>
<script language="javascript" type="text/javascript" src="../js/basic.js"></script>
<script language="javascript" type="text/javascript" src="../js/HouqianTable.js"></script>
<script language="javascript" type="text/javascript" src="../js/HouqianTab.js"></script>
<script language="javascript" type="text/javascript" src="../js/DatePicker/WdatePicker.js"></script>