var ioc={
	dataSource:{
		type:"com.alibaba.druid.pool.DruidDataSource",
		fields:{
			driverClassName:'com.mysql.jdbc.Driver',
			url:'jdbc:mysql://localhost:3306/sicnutz',
			username:'root',
			password:'123456'
		},
		events:{
			depose:'close'
		}
	},
	dao:{
		type:"org.nutz.dao.impl.NutDao",
		args:[{refer:"dataSource"}]
	},
	freeMaker:{
		type:'freemarker.template.Configuration'
	},
	defaultAuth:{
		type:'org.apache.commons.mail.DefaultAuthenticator',
		args:["zhuweionline@163.com","zhuwei19870923"]
	},
	multiMail:{
		type:'org.apache.commons.mail.MultiPartEmail',
		fields:{
			hostName:'smtp.163.com',
			charset:'utf-8',
			from:'zhuweionline@163.com',
			authenticator:{refer:'defaultAuth'}
		}
	},
	attachMail:{
		type:'org.apache.commons.mail.EmailAttachment'
	}
};