{
	"myChain":{
		"ps":[
			"org.nutz.mvc.impl.processor.UpdateRequestAttributesProcessor",
			"org.nutz.mvc.impl.processor.EncodingProcessor",
			"org.nutz.mvc.impl.processor.ModuleProcessor",
			"org.nutz.mvc.impl.processor.ActionFiltersProcessor",
			"org.nutz.mvc.impl.processor.AdaptorProcessor",
			"com.laivi.sic.action.interceptor.ExceptionProcess",
			"org.nutz.mvc.impl.processor.ViewProcessor"
		],
		"error":'org.nutz.mvc.impl.processor.FailProcessor'
	}	
}